[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "low_res_phenotyping_tools"
version = "0.0.1"
authors = [
  { name="Dave Mets", email="dave.mets@arcadiascience.com" },
]
description = "A set of tools for making phenotyping assays using the Arcadia phenotypeomat."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Arcadia-Science/arcadia-phenotypeomat-protocol"
"Bug Tracker" = "https://github.com/Arcadia-Science/arcadia-phenotypeomat/issues"
