[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "arcadia-phenotypeomat-protocol"
version = "0.0.1"
dependencies = [
"opencv >= 4.5.4", "pyserial >= 3.5", "Teledyne/Flir Spinnaker SDK >= 2.3"
]
authors = [
  { name="Dave Mets", email="dave.mets@arcadiascience.com" },
]
description = "A set of tools for making phenotyping assays using the Arcadia phenotype-o-mat."
readme = "README.md"
requires-python = "3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Arcadia-Science/arcadia-phenotypeomat-protocol"
"Bug Tracker" = "https://github.com/Arcadia-Science/arcadia-phenotypeomat-protocol/issues"
